name: covid19
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: any
  intl: any
  flutter_svg: any
  flutter_spinkit: any
  font_awesome_flutter: any
  pie_chart: any


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
